config/routes.rb
ContactForm::Application.routes.draw do
  resources :inquiries

end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_presence_of :subject
  validates_presence_of :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def index
    @inquiries = Inquiry.all
  end

  def show
    @inquiry = Inquiry.find(params[:id])
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save
      redirect_to @inquiry, notice: 'Inquiry was successfully saved'
    else
      render action: 'new'
    end
  end

  def new
    @inquiry = Inquiry.new
  end

  def update
    @inquiry = Inquiry.find(params[:id])
    if @inquiry.update(inquiry_params)
      redirect_to @inquiry, notice: 'Inquiry was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def edit
    @inquiry = Inquiry.find(params[:id])
  end

  def destroy
    @inquiry = Inquiry.find(params[:id])
    @inquiry.destroy
    redirect_to inquiries_url
  end

  private
    def inquiry_params
      params.require(:inquiry).permit(:first_name, :last_name, :email, :subject, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/_form.html.erb.html.erb
<%= form_for(@inquiry) do |f| %>
  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
      <% @inquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label(:first_name, "First Name") %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label(:last_name, "Last Name") %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label(:email, "Email") %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label(:subject, "Subject") %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label(:description, "Description") %><br>
    <%= f.text_field :description %>
  </div>
  <div clas="action">
    <%= f.submit %>
  </div>
<% end %>

app/views/inquiries/edit.html.erb
<h1>Edit Inquiry</h1>
<%= render 'form.html.erb' %>

app/views/inquiries/index.html.erb
<h1>All Inquiries</h1>

<%= link_to 'New Inquiry', new_inquiry_path, class: "button radius" %>

<table>
  <thead>
    <tr>
      <th>Last Name</th>
      <th>First Name</th>
      <th>Email</th>
      <th>Subject</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @inquiries.each do |inquiry| %>
      <tr>
        <td><%= inquiry.last_name %></td>
        <td><%= inquiry.first_name %></td>
        <td><%= inquiry.email %></td>
        <td><%= inquiry.subject %></td>
        <td><%= inquiry.description %></td>
        <td><%= link_to 'Show', inquiry %></td>
        <td><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td>
        <td><%= link_to 'Delete', inquiry_path(inquiry), method: :delete %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/inquiries/new.html.erb
<%= render 'form.html.erb' %>

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:
    <%= "#{@inquiry.last_name}, #{@inquiry.first_name}" %></strong>
</p>
<p>
  Email:
    <%= @inquiry.email %>
</p>
<p>
  Subject:
    <%= @inquiry.subject %>
</p>
<p>
  Description:
    <%= @inquiry.description %>
</p>

<%= link_to 'Edit', edit_inquiry_path(@inquiry) %> |
<%= link_to 'Inquiries', inquiries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactForm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>